name: Unit Tests On Matrix

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        project: [tests/ArrowDbCore.Tests.Unit/ArrowDbCore.Tests.Unit.csproj, tests/ArrowDbCore.Tests.Unit.Isolated/ArrowDbCore.Tests.Unit.Isolated.csproj]
    uses: dusrdev/actions/.github/workflows/reusable-dotnet-test-mtp.yaml@main
    with:
      platform: ${{ matrix.platform }}
      dotnet-version: 9.0.x
      test-project-path: ${{ matrix.project }}

  integrity-tests:
    uses: dusrdev/actions/.github/workflows/reusable-dotnet-test-mtp.yaml@main
    with:
      platform: ubuntu-latest
      dotnet-version: 9.0.x
      test-project-path: tests/ArrowDbCore.Tests.Integrity/ArrowDbCore.Tests.Integrity.csproj

  aot-trimming:
    env:
      PROJECT: tests/ArrowDbCore.Tests.Analyzers/ArrowDbCore.Tests.Analyzers.csproj

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore ${{ env.PROJECT }}

      - name: Build As Release
        run: dotnet build ${{ env.PROJECT }} --configuration Release