name: Unit Tests On Matrix

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-main:
    uses: dusrdev/actions/.github/workflows/reusable-dotnet-test-matrix-mtp.yaml@main
    with:
      dotnet-version: 9.0.x
      test-project-path: tests/ArrowDbCore.Tests.Unit/ArrowDbCore.Tests.Unit.csproj

  test-isolated:
    uses: dusrdev/actions/.github/workflows/reusable-dotnet-test-matrix-mtp.yaml@main
    with:
      dotnet-version: 9.0.x
      test-project-path: tests/ArrowDbCore.Tests.Unit.Isolated/ArrowDbCore.Tests.Unit.Isolated.csproj